name: Jest Test

on: [push, pull_request]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-env

      - name: Run Jest Tests
        run: npm run test:ci

      - name: Upload Jest Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: coverage

          # If Branch Protection Rules: Require status checks to pass before merging is off
      # - name: Fail PR if Tests Fail
      #   if: failure()
      #   run: exit 1
