name: Jest Test

on: [push, pull_request]

jobs:
  Jest:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Jest Tests
        run: npm run test:ci

      - name: Upload Jest Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: coverage

          # If Branch Protection Rules: Require status checks to pass before merging is off
      # - name: Fail PR if Tests Fail
      #   if: failure()
      #   run: exit 1
